var monsterSpawnScenario = [
                  {type:"vampire",
                  time: 0.5,
                  x: 0.95,
                  y: 0.8},
                   {type:"zombie",
                  time: 3.0,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 2.0,
                  x: 0.95,
                  y: 0.5},
                  {type:"skull",
                  time: 3,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 2,
                  x: 0.95,
                  y: 0.5},
                  {type:"vampire",
                  time: 3,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 4.0,
                  x: 0.95,
                  y: 0.8},
                  {type:"zombie",
                  time: 1.0,
                  x: 0.95,
                  y: 0.5},
                  {type:"vampire",
                  time: 5,
                  x: 0.95,
                  y: 0.5},
                  //second wave
                 {type:"zombie",
                  time: 5.0,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 0.1,
                  x: 0.95,
                  y: 0.8},
                  {type:"vampire",
                  time: 5,
                  x: 0.95,
                  y: 0.25},
                  {type:"vampire",
                  time: 0.1,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 2,
                  x: 0.95,
                  y: 0.5},
                  {type:"skull",
                  time: 2,
                  x: 0.95,
                  y: 0.5},
                  {type:"zombie",
                  time: 3.0,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 0.1,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 1,
                  x: 0.95,
                  y: 0.5},
                  {type:"skull",
                  time: 2,
                  x: 0.95,
                  y: 0.5},
                  //3rd wave
                  {type:"vampire",
                  time: 5,
                  x: 0.95,
                  y: 0.5},
                  {type:"zombie",
                  time: 3.0,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 2.0,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 3,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 2,
                  x: 0.95,
                  y: 0.5},
                  {type:"vampire",
                  time: 3,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 4.0,
                  x: 0.95,
                  y: 0.8},
                  {type:"zombie",
                  time: 1.0,
                  x: 0.95,
                  y: 0.25},
                  {type:"vampire",
                  time: 5,
                  x: 0.95,
                  y: 0.5},
                  //boss wave
                  {type:"vampire",
                  time: 5,
                  x: 0.95,
                  y: 0.5},
                  {type:"zombie",
                  time: 4.0,
                  x: 0.95,
                  y: 0.8},
                  {type:"zombie",
                  time: 5,
                  x: 0.95,
                  y: 0.25},
                  {type:"skeleton",
                  time: 5,
                  x: 0.95,
                  y: 0.5},
                  {type:"vampire",
                  time: 2,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 1,
                  x: 0.95,
                  y: 0.8},
                  {type:"zombie",
                  time: 0.6,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 1,
                  x: 0.95,
                  y: 0.5},
                  {type:"zombie",
                  time: 0.5,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 1.0,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 1.5,
                  x: 0.95,
                  y: 0.5},
                  {type:"vampire",
                  time: 0.5,
                  x: 0.95,
                  y: 0.25},
                  {type:"zombie",
                  time: 1,
                  x: 0.95,
                  y: 0.8},
                  {type:"skull",
                  time: 0.3,
                  x: 0.95,
                  y: 0.25},
                  {type:"skull",
                  time: 1,
                  x: 0.95,
                  y: 0.5},
                  {type:"skull",
                  time: 1,
                  x: 0.95,
                  y: 0.25},
                  {type:"skull",
                  time: 1,
                  x: 0.95,
                  y: 0.25},
                  {type:"vampire",
                  time: 7,
                  x: 0.95,
                  y: 0.5},
                  ];
