var monsterSpawnScenario = [
                  {type:"vampire",
                  time: 0.5,
                  x: 0.85,
                  y: 0.8},
                  {type:"zombie",
                  time: 2.0,
                  x: 0.85,
                  y: 0.25},
                  {type:"zombie",
                  time: 1.0,
                  x: 0.85,
                  y: 0.5},
                  {type:"skull",
                  time: 2,
                  x: 0.85,
                  y: 0.8},
                  {type:"skull",
                  time: 3,
                  x: 0.85,
                  y: 0.5},
                  {type:"vampire",
                  time: 1,
                  x: 0.85,
                  y: 0.25},
                  ];
