var monsterSpawnScenario = [
                  {type:"vampire",
                  time: 0.5,
                  x: 0.85,
                  y: 0.8},
                  {type:"zombie",
                  time: 2.0,
                  x: 0.85,
                  y: 0.25},
                  {type:"zombie",
                  time: 3.0,
                  x: 0.85,
                  y: 0.5},
                  {type:"skeleton",
                  time: 6,
                  x: 0.85,
                  y: 0.8},
                  {type:"skull",
                  time: 9,
                  x: 0.85,
                  y: 0.5},
                  {type:"vampire",
                  time: 9,
                  x: 0.85,
                  y: 0.25},
                  ];
